# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hand
  joint_model_group_pose: hand_ready_position
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - schunk_pg70_finger_left_joint
    - schunk_pg70_finger_right_joint
    
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    constraints:
      stopped_velocity_tolerance: 0

  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - schunk_pg70_finger_left_joint
      - schunk_pg70_finger_right_joint

arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_position_controller:
  type: position_controllers/JointPositionController
  joints:
    schunk_pg70_finger_left_joint
  gains:
    schunk_pg70_finger_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1